name: saucectl espresso tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Saucectl RUN Sauce Cloud
        uses: saucelabs/saucectl-run-action@v3
        with:
          concurrency: 10

  cucumber-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Espresso with Cucumber
        uses: saucelabs/saucectl-run-action@v3
        with:
          concurrency: 10
          working-directory: ./examples/cucumber
